### ISSUE TITLE
Error: Cannot find module 'swig'

### ISSUE THREAD

**Issue by Binom777** [brainfucker/nodejs.ru#12]
C:\Users\Binom\GoogleDrv\Projects\nodejs\ru-doc\nodejs.ru>node init.js
module.js:341
    throw err;
    ^

Error: Cannot find module 'swig'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Binom\GoogleDrv\Projects\nodejs\ru-doc\nodejs.ru\init.js:5:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)`
`

После инсталляции и запуска вот такая вот петрушка.

**Comment by grebenschikov** [comment]
Вы сделали npm install внутри папки nodejs.ru?

Попробуйте еще разок сделать следующее:
```
git clone https://github.com/brainfucker/nodejs.ru
cd nodejs.ru/
npm install
node init.js
```
